version: '3.7'
 
services:
      app:
        build:
          args:
            user: user
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: homestead
        container_name: homestead-app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
          - db
        volumes:
          - ./:/var/www
        networks:
          - homestead

      db:
        image: mysql:5.7
        container_name: homestead-db
        restart: unless-stopped
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        volumes:
          - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
          - homestead

      nginx:
        image: nginx:1.17-alpine
        container_name: homestead-nginx
        restart: unless-stopped
        ports:
          - 8080:80
        volumes:
          - ./:/var/www
          - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
          - homestead

networks:
  homestead:
    driver: bridge

